name: Pull Request
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  integrity-checks:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Check doc
        run: deno task check-doc

      - name: Run tests
        run: |
          deno test -A --coverage=cov_profile
          deno coverage cov_profile --lcov --output=cov_profile.lcov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
