name: Publish
on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint --ignore=\*\*\/\*_test.ts

      - name: Run tests
        run: deno test -A

      - name: Check publishing requirements
        run: npx jsr publish --dry-run

      - name: Publish package
        run: npx jsr publish
